language: clojure
lein: lein
cache:
  directories:
    - $HOME/.m2
jdk:
  # - oraclejdk8
  # - oraclejdk9
  - oraclejdk11

before_script:
  - psql -c 'create database yetibot;' -U postgres

env:
  - YETIBOT_DB_URL="postgresql://postgres@localhost:5432/yetibot"

before_deploy:
  - git status
    # clean up annoying package-lock.json changes
  - git reset --hard
  - lein deps # ensure npm deps are fetched
  - ls -al node_modules/yetibot-dashboard/build
  - ls -al node_modules/yetibot-dashboard/build/index.html
  - git status
  - git stash

deploy:
  provider: script
  # deploy is a single script to run - not an array of commands
  script: lein release
  # keep node_modules so it's included as a resource in the jar
  skip_cleanup: true
  on:
    branch: master
    # ensure we only attempt to deploy once using jdk 11
    jdk: oraclejdk11

services:
  - postgresql

after_success:
- CLOVERAGE_VERSION=1.1.1 lein with-profile +test cloverage --codecov --runner midje
- bash <(curl -s https://codecov.io/bash)
