name: test
on: push


jobs:
  test:
    name: Test yetibot/core
    runs-on: ubuntu-latest
    container: clojure:openjdk-11
    services:
      postgres:
        image: postgres:11
        ports:
          # assigns a random free host port
          - 5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_DB: yetibot
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
    steps:
      - name: Check out
        # checkout@v2 does not pull the .git directory into the working dir
        uses: actions/checkout@v1
      - name: debug
        run: |
          echo $YETIBOT_DB_URL
          ls -al
          echo $SHELL
          which git
        env:
          YETIBOT_DB_URL: postgres://postgres@localhost:${{ job.services.postgres.ports['5432'] }}/yetibot
      - name: lein test
        run: lein test
        env:
          YETIBOT_DB_URL: postgres://postgres@localhost:${{ job.services.postgres.ports['5432'] }}/yetibot

